// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',           // Plus sécurisé que implicite
  },
  global: {
    headers: {
      'x-application-name': 'vovinam-ugb',
    },
  },
  db: {
    schema: 'public',
  },
});

// ── Intercepteur Auth Global
// Déconnecte proprement l'utilisateur si le token JWT expire et ne peut pas être rafraîchi
supabase.auth.onAuthStateChange((event) => {
  if (event === 'TOKEN_REFRESHED') {
    // Silencieux — le token a été rafraîchi automatiquement
    console.debug('[AUTH] Token rafraîchi avec succès');
  }

  if (event === 'SIGNED_OUT') {
    // Vider les données locales
    localStorage.removeItem('supabase.auth.token');
    // Redirection uniquement si sur page protégée
    if (window.location.pathname.startsWith('/dashboard')) {
      window.location.href = '/auth';
    }
  }
});